package com.newlife.Connect_multiple.entity;

import lombok.Data;

import javax.persistence.*;
import java.sql.Timestamp;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "cpu")
public class PerformanceCpu {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    @Column(name = "id_probe")
    private Integer idProbe;
    @Column(name = "time", columnDefinition = "datetime")
    private LocalDateTime time;
    @Column(name = "unix_time")
    private String unixTime;
    @Column(name = "check_average_load")
    private Integer check;
    @Column(name = "cpu")
    public Double cpu;
    @Column(name = "cpu0")
    public Double cpu0;
    @Column(name = "cpu_1")
    public Double cpu1;
    @Column(name = "cpu_2")
    public Double cpu2;
    @Column(name = "cpu_3")
    public Double cpu3;
    @Column(name = "cpu_4")
    public Double cpu4;
    @Column(name = "cpu_5")
    public Double cpu5;
    @Column(name = "cpu_6")
    public Double cpu6;
    @Column(name = "cpu_7")
    public Double cpu7;
    @Column(name = "cpu_8")
    public Double cpu8;
    @Column(name = "cpu_9")
    public Double cpu9;
    @Column(name = "cpu_10")
    public Double cpu10;
    @Column(name = "cpu_11")
    public Double cpu11;
    @Column(name = "cpu_12")
    public Double cpu12;
    @Column(name = "cpu_13")
    public Double cpu13;
    @Column(name = "cpu_14")
    public Double cpu14;
    @Column(name = "cpu_15")
    public Double cpu15;
    @Column(name = "cpu_16")
    public Double cpu16;
    @Column(name = "cpu_17")
    public Double cpu17;
    @Column(name = "cpu_18")
    public Double cpu18;
    @Column(name = "cpu_19")
    public Double cpu19;
    @Column(name = "cpu_20")
    public Double cpu20;
    @Column(name = "cpu_21")
    public Double cpu21;
    @Column(name = "cpu_22")
    public Double cpu22;
    @Column(name = "cpu_23")
    public Double cpu23;
    @Column(name = "cpu_24")
    public Double cpu24;
    @Column(name = "cpu_25")
    public Double cpu25;
    @Column(name = "cpu_26")
    public Double cpu26;
    @Column(name = "cpu_27")
    public Double cpu27;
    @Column(name = "cpu_28")
    public Double cpu28;
    @Column(name = "cpu_29")
    public Double cpu29;
    @Column(name = "cpu_30")
    public Double cpu30;
    @Column(name = "cpu_31")
    public Double cpu31;
    @Column(name = "cpu_32")
    public Double cpu32;
    @Column(name = "cpu_33")
    public Double cpu33;
    @Column(name = "cpu_34")
    public Double cpu34;
    @Column(name = "cpu_35")
    public Double cpu35;
    @Column(name = "cpu_36")
    public Double cpu36;
    @Column(name = "cpu_37")
    public Double cpu37;
    @Column(name = "cpu_38")
    public Double cpu38;
    @Column(name = "cpu_39")
    public Double cpu39;
    @Column(name = "cpu_40")
    public Double cpu40;
    @Column(name = "cpu_41")
    public Double cpu41;
    @Column(name = "cpu_42")
    public Double cpu42;
    @Column(name = "cpu_43")
    public Double cpu43;
    @Column(name = "cpu_44")
    public Double cpu44;
    @Column(name = "cpu_45")
    public Double cpu45;
    @Column(name = "cpu_46")
    public Double cpu46;
    @Column(name = "cpu_47")
    public Double cpu47;
    @Column(name = "cpu_48")
    public Double cpu48;
    @Column(name = "cpu_49")
    public Double cpu49;
    @Column(name = "cpu_50")
    public Double cpu50;
    @Column(name = "cpu_51")
    public Double cpu51;
    @Column(name = "cpu_52")
    public Double cpu52;
    @Column(name = "cpu_53")
    public Double cpu53;
    @Column(name = "cpu_54")
    public Double cpu54;
    @Column(name = "cpu_55")
    public Double cpu55;
    @Column(name = "cpu_56")
    public Double cpu56;
    @Column(name = "cpu_57")
    public Double cpu57;
    @Column(name = "cpu_58")
    public Double cpu58;
    @Column(name = "cpu_59")
    public Double cpu59;
    @Column(name = "cpu_60")
    public Double cpu60;
    @Column(name = "cpu_61")
    public Double cpu61;
    @Column(name = "cpu_62")
    public Double cpu62;
    @Column(name = "cpu_63")
    public Double cpu63;
    @Column(name = "cpu_64")
    public Double cpu64;
}
